# This is a basic workflow to help you get started with Actions
name: Recent Activity

on:
  schedule:
    - cron: '0 * * * *'  # Toutes les heures
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with recent activity
    runs-on: ubuntu-latest
    steps:
      - uses: Readme-Workflows/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
