name: Update README with Recent GitHub Activity

on:
  schedule:
    - cron: '*/30 * * * *'  # Toutes les 30 minutes
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Recent GitHub Activity - Profile Readme
        uses: Readme-Workflows/recent-activity@v2.4.1
        with:
          GH_USERNAME: chamse22ine
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
