name: Update README

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GH_USERNAME: chamse22ine
          COMMIT_NAME: GitHub Actions Bot
          COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          COMMIT_MSG: "⚡ Update README with the recent activity"
          EMPTY_COMMIT_MSG: "📝 empty commit to keep workflow active after 60 days of no activity"
          MAX_LINES: 10
          TARGET_FILE: README.md
